import { Link } from "react-router-dom";

export function TermsOfService() {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 py-16 px-4">
      <div className="max-w-3xl mx-auto">
        <div className="mb-10">
          <Link to="/" className="text-sm text-slate-500 hover:text-slate-700 dark:hover:text-slate-300">
            ← Back to Home
          </Link>
        </div>

        <h1 className="text-4xl font-black text-slate-900 dark:text-white mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-500 dark:text-slate-400 mb-10">Last updated: April 10, 2026</p>

        <div className="prose prose-slate dark:prose-invert max-w-none space-y-8 text-slate-700 dark:text-slate-300">

          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By creating an account or using ResumeMatch Pro ("the Service"), you agree to these Terms of Service. If you do not agree, please do not use the Service. These terms apply to the website at{" "}
              <a href="https://landyourjob.zenlead.in" className="text-blue-600 dark:text-blue-400 underline">
                landyourjob.zenlead.in
              </a>{" "}
              and the ResumeMatch Pro Chrome extension.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">2. Description of Service</h2>
            <p>
              ResumeMatch Pro provides AI-powered resume tailoring, ATS score analysis, job search assistance, and related tools. The service uses Google Gemini AI to process resume and job description data.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">3. Account Registration</h2>
            <ul className="list-disc list-inside space-y-1">
              <li>You must be at least 18 years old to create an account</li>
              <li>You are responsible for maintaining the security of your account credentials</li>
              <li>You must provide accurate information during registration</li>
              <li>One account per person — duplicate accounts may be terminated</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">4. Subscriptions and Billing</h2>
            <ul className="list-disc list-inside space-y-1">
              <li>Subscriptions are billed on the cycle shown at checkout (monthly or yearly)</li>
              <li>Subscriptions <strong>auto-renew</strong> at the end of each billing period unless cancelled</li>
              <li>You can cancel your subscription at any time from your Billing page — cancellation takes effect at the end of the current billing period</li>
              <li>Prices are shown in INR or your selected currency at checkout</li>
              <li>We reserve the right to change pricing with 30 days' notice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">5. Credits</h2>
            <ul className="list-disc list-inside space-y-1">
              <li>Credits are consumed when you use AI features (resume tailoring, ATS scoring, job analysis)</li>
              <li>Credits are non-refundable once consumed</li>
              <li>Unused credits from a subscription cycle do not roll over unless specified in your plan</li>
              <li>One-time credit purchases are non-expiring</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">6. AI-Generated Content</h2>
            <ul className="list-disc list-inside space-y-1">
              <li>Tailored resumes and suggestions are generated by AI and provided as-is</li>
              <li>You should review all AI-generated content before submitting job applications</li>
              <li>We do not guarantee that AI-generated resumes will result in job interviews or offers</li>
              <li>You own all resume content you upload and all tailored resumes you download</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">7. Acceptable Use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc list-inside space-y-1">
              <li>Resell, sublicense, or distribute access to the Service</li>
              <li>Use automated scripts or bots to bulk-generate resumes</li>
              <li>Attempt to reverse-engineer, scrape, or extract data from the Service</li>
              <li>Use the Service for any unlawful purpose</li>
              <li>Upload content that infringes third-party intellectual property rights</li>
              <li>Impersonate another person in job applications</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">8. Chrome Extension</h2>
            <ul className="list-disc list-inside space-y-1">
              <li>The extension reads job description content only when you click "Analyse Job"</li>
              <li>The extension requires a valid ResumeMatch Pro account to function</li>
              <li>Extension features are subject to availability and may change over time</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">9. Disclaimer of Warranties</h2>
            <p>
              The Service is provided "as is" without warranties of any kind. We do not warrant that the Service will be uninterrupted, error-free, or that AI-generated content will be accurate or suitable for your specific use case.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">10. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, ZenLead shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to loss of income or employment opportunities.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">11. Termination</h2>
            <p>
              We may suspend or terminate your account if you violate these terms. You may close your account at any time. Upon termination, your data will be deleted in accordance with our{" "}
              <Link to="/privacy-policy" className="text-blue-600 dark:text-blue-400 underline">Privacy Policy</Link>.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">12. Governing Law</h2>
            <p>
              These terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in India.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-3">13. Contact</h2>
            <p>
              For questions about these terms:{" "}
              <a href="mailto:support@zenlead.in" className="text-blue-600 dark:text-blue-400 underline">
                support@zenlead.in
              </a>
            </p>
          </section>

        </div>

        <div className="mt-12 pt-8 border-t border-slate-200 dark:border-slate-800 flex flex-wrap gap-4 text-sm text-slate-500">
          <Link to="/privacy-policy" className="hover:text-slate-700 dark:hover:text-slate-300">Privacy Policy</Link>
          <Link to="/refund-policy" className="hover:text-slate-700 dark:hover:text-slate-300">Refund Policy</Link>
          <Link to="/contact" className="hover:text-slate-700 dark:hover:text-slate-300">Contact</Link>
        </div>
      </div>
    </div>
  );
}
